In [1]:
import numpy as np
from numpy.random import random
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import SGD

Using TensorFlow backend.


In [2]:
w1= 2.
w2= 3.
b = 1
x = random((30,2))
y = np.dot(x, [w1,w2])+b

In [3]:
x[:5]

array([[ 0.77830557,  0.91471129],
       [ 0.4490322 ,  0.28770761],
       [ 0.48430345,  0.8722434 ],
       [ 0.62590707,  0.87376084],
       [ 0.11304528,  0.5517469 ]])

In [4]:
y[:5]

array([ 5.30074501,  2.76118723,  4.58533709,  4.87309665,  2.88133125])

In [5]:
lm = Sequential([Dense(1, input_shape=(2,))])
lm.compile(optimizer=SGD(lr=0.1), loss='mse')

In [6]:
lm.evaluate(x,y, verbose=0)

10.854475021362305

In [7]:
lm.fit(x,y,nb_epoch=5, batch_size=1)

Epoch 1/5
30/30 [==============================] - 0s - loss: 0.8631     
Epoch 2/5
30/30 [==============================] - 0s - loss: 0.1134     
Epoch 3/5
30/30 [==============================] - 0s - loss: 0.0375     
Epoch 4/5
30/30 [==============================] - 0s - loss: 0.0161     
Epoch 5/5
30/30 [==============================] - 0s - loss: 0.0067     


In [8]:
lm.evaluate(x,y, verbose=0)

0.0031431110110133886

In [9]:
w = lm.get_weights()
p_w1,p_w2 = w[0]
p_b = w[1]
w

[array([[ 1.83354652],
        [ 2.96883512]], dtype=float32), array([ 1.09164631], dtype=float32)]

In [10]:
p_w1 

array([ 1.83354652], dtype=float32)

In [11]:
p_w2

array([ 2.96883512], dtype=float32)

In [12]:
p_b

array([ 1.09164631], dtype=float32)